from PyQt5 import QtCore, QtGui, QtWidgets
from mplwidget import mplwidget

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1100, 582)
        MainWindow.setMinimumSize(QtCore.QSize(1000, 582))
        MainWindow.setStyleSheet("font: 8pt \"Verdana\";")
        MainWindow.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.stepSpin = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.stepSpin.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.stepSpin.setButtonSymbols(QtWidgets.QAbstractSpinBox.UpDownArrows)
        self.stepSpin.setDecimals(3)
        self.stepSpin.setMinimum(0.001)
        self.stepSpin.setMaximum(5.0)
        self.stepSpin.setSingleStep(0.001)
        self.stepSpin.setProperty("value", 0.01)
        self.stepSpin.setObjectName("stepSpin")
        self.gridLayout.addWidget(self.stepSpin, 0, 1, 1, 1)
        self.tfSpin = QtWidgets.QSpinBox(self.centralwidget)
        self.tfSpin.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.tfSpin.setMaximum(10000)
        self.tfSpin.setSingleStep(10)
        self.tfSpin.setProperty("value", 50)
        self.tfSpin.setObjectName("tfSpin")
        self.gridLayout.addWidget(self.tfSpin, 2, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.tsSpin = QtWidgets.QSpinBox(self.centralwidget)
        self.tsSpin.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.tsSpin.setMaximum(99)
        self.tsSpin.setObjectName("tsSpin")
        self.gridLayout.addWidget(self.tsSpin, 1, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout, 0, 0, 1, 1)
        self.widget = mplwidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget.sizePolicy().hasHeightForWidth())
        self.widget.setSizePolicy(sizePolicy)
        self.widget.setObjectName("widget")
        self.gridLayout_3.addWidget(self.widget, 0, 1, 4, 1)
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setMinimumSize(QtCore.QSize(351, 261))
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.point1 = QtWidgets.QGroupBox(self.groupBox)
        self.point1.setMinimumSize(QtCore.QSize(331, 81))
        self.point1.setObjectName("point1")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.point1)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_4 = QtWidgets.QLabel(self.point1)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 0, 0, 1, 1)
        self.x1Spin = QtWidgets.QDoubleSpinBox(self.point1)
        self.x1Spin.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.x1Spin.setMinimum(-25.0)
        self.x1Spin.setMaximum(25.0)
        self.x1Spin.setProperty("value", 1.0)
        self.x1Spin.setObjectName("x1Spin")
        self.gridLayout_2.addWidget(self.x1Spin, 0, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.point1)
        self.label_7.setObjectName("label_7")
        self.gridLayout_2.addWidget(self.label_7, 0, 2, 1, 1)
        self.y1Spin = QtWidgets.QDoubleSpinBox(self.point1)
        self.y1Spin.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.y1Spin.setMinimum(-25.0)
        self.y1Spin.setMaximum(25.0)
        self.y1Spin.setProperty("value", 1.0)
        self.y1Spin.setObjectName("y1Spin")
        self.gridLayout_2.addWidget(self.y1Spin, 0, 3, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.point1)
        self.label_10.setObjectName("label_10")
        self.gridLayout_2.addWidget(self.label_10, 0, 4, 1, 1)
        self.z1Spin = QtWidgets.QDoubleSpinBox(self.point1)
        self.z1Spin.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.z1Spin.setMinimum(-25.0)
        self.z1Spin.setMaximum(25.0)
        self.z1Spin.setProperty("value", 1.0)
        self.z1Spin.setObjectName("z1Spin")
        self.gridLayout_2.addWidget(self.z1Spin, 0, 5, 1, 1)
        self.addPointBtn = QtWidgets.QPushButton(self.point1)
        self.addPointBtn.setObjectName("addPointBtn")
        self.gridLayout_2.addWidget(self.addPointBtn, 1, 0, 1, 6)
        self.verticalLayout.addWidget(self.point1)
        self.initialPointsTbl = QtWidgets.QTableWidget(self.groupBox)
        self.initialPointsTbl.setRowCount(0)
        self.initialPointsTbl.setColumnCount(3)
        self.initialPointsTbl.setObjectName("initialPointsTbl")
        self.initialPointsTbl.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.initialPointsTbl.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.verticalLayout.addWidget(self.initialPointsTbl)
        self.gridLayout_3.addWidget(self.groupBox, 1, 0, 1, 1)
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_2.sizePolicy().hasHeightForWidth())
        self.groupBox_2.setSizePolicy(sizePolicy)
        self.groupBox_2.setMinimumSize(QtCore.QSize(351, 151))
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.playBtn = QtWidgets.QPushButton(self.groupBox_2)
        self.playBtn.setObjectName("playBtn")
        self.gridLayout_6.addWidget(self.playBtn, 0, 1, 1, 1)
        self.initBtn = QtWidgets.QPushButton(self.groupBox_2)
        self.initBtn.setObjectName("initBtn")
        self.gridLayout_6.addWidget(self.initBtn, 0, 0, 1, 1)
        self.saveBtn = QtWidgets.QPushButton(self.groupBox_2)
        self.saveBtn.setObjectName("saveBtn")
        self.gridLayout_6.addWidget(self.saveBtn, 0, 2, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.groupBox_2)
        self.label_14.setObjectName("label_14")
        self.gridLayout_6.addWidget(self.label_14, 1, 0, 1, 2)
        self.label_15 = QtWidgets.QLabel(self.groupBox_2)
        self.label_15.setObjectName("label_15")
        self.gridLayout_6.addWidget(self.label_15, 3, 0, 1, 2)
        self.aniSpeedBtn = QtWidgets.QSlider(self.groupBox_2)
        self.aniSpeedBtn.setOrientation(QtCore.Qt.Horizontal)
        self.aniSpeedBtn.setMinimum(1)
        self.aniSpeedBtn.setMaximum(100)
        self.aniSpeedBtn.setValue(2)
        self.aniSpeedBtn.setObjectName("aniSpeedBtn")
        self.gridLayout_6.addWidget(self.aniSpeedBtn, 4, 0, 1, 3)
        self.rotSpeedBtn = QtWidgets.QSlider(self.groupBox_2)
        self.rotSpeedBtn.setOrientation(QtCore.Qt.Horizontal)
        self.rotSpeedBtn.setMaximum(5)
        self.rotSpeedBtn.setValue(2)
        self.rotSpeedBtn.setObjectName("rotSpeedBtn")
        self.gridLayout_6.addWidget(self.rotSpeedBtn, 2, 0, 1, 3)
        self.gridLayout_3.addWidget(self.groupBox_2, 2, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.calculateBtn = QtWidgets.QPushButton(self.centralwidget)
        self.calculateBtn.setAutoDefault(True)
        self.calculateBtn.setDefault(True)
        self.calculateBtn.setObjectName("calculateBtn")
        self.horizontalLayout.addWidget(self.calculateBtn)
        self.gridLayout_3.addLayout(self.horizontalLayout, 3, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 896, 19))
        self.menuBar.setObjectName("menuBar")
        self.menuFile = QtWidgets.QMenu(self.menuBar)
        self.menuFile.setObjectName("menuFile")
        self.menuAnimation = QtWidgets.QMenu(self.menuBar)
        self.menuAnimation.setObjectName("menuAnimation")
        MainWindow.setMenuBar(self.menuBar)
        self.about_Action = QtWidgets.QAction(MainWindow)
        self.about_Action.setShortcut("Ctrl+Shift+A")
        self.about_Action.setObjectName("about_Action")
        self.openCalc_Action = QtWidgets.QAction(MainWindow)
        self.openCalc_Action.setObjectName("openCalc_Action")
        self.close_Action = QtWidgets.QAction(MainWindow)
        self.close_Action.setShortcut("Ctrl+Q")
        self.close_Action.setObjectName("close_Action")
        self.aniSave_Action = QtWidgets.QAction(MainWindow)
        self.aniSave_Action.setShortcut("Ctrl+S")
        self.aniSave_Action.setObjectName("aniSave_Action")
        self.aniPlay_Action = QtWidgets.QAction(MainWindow)
        self.aniPlay_Action.setEnabled(False)
        self.aniPlay_Action.setObjectName("aniPlay_Action")
        self.aniPlay_Action.setShortcut("Ctrl+P")
        self.aniInitAction = QtWidgets.QAction(MainWindow)
        self.aniInitAction.setShortcut("Ctrl+I")
        self.aniInitAction.setObjectName("aniInitAction")
        self.menuFile.addAction(self.about_Action)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.close_Action)
        self.menuAnimation.addAction(self.aniInitAction)
        self.menuAnimation.addAction(self.aniPlay_Action)
        self.menuAnimation.addSeparator()
        self.menuAnimation.addAction(self.aniSave_Action)
        self.menuBar.addAction(self.menuFile.menuAction())
        self.menuBar.addAction(self.menuAnimation.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.stepSpin, self.tsSpin)
        MainWindow.setTabOrder(self.tsSpin, self.tfSpin)
        MainWindow.setTabOrder(self.tfSpin, self.x1Spin)
        MainWindow.setTabOrder(self.x1Spin, self.y1Spin)
        MainWindow.setTabOrder(self.y1Spin, self.z1Spin)
        MainWindow.setTabOrder(self.z1Spin, self.calculateBtn)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Interactive Lorenz Attractor"))
        self.label.setText(_translate("MainWindow", "Step size:"))
        self.label_2.setText(_translate("MainWindow", "Starting Time:"))
        self.label_3.setText(_translate("MainWindow", "Finish Time:"))
        self.groupBox.setTitle(_translate("MainWindow", "Initial Conditions"))
        self.point1.setTitle(_translate("MainWindow", "Add point"))
        self.label_4.setText(_translate("MainWindow", "X:"))
        self.label_7.setText(_translate("MainWindow", "Y:"))
        self.label_10.setText(_translate("MainWindow", "Z:"))
        self.addPointBtn.setText(_translate("MainWindow", "Add"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Figure Controls"))
        self.playBtn.setText(_translate("MainWindow", "Play"))
        self.initBtn.setText(_translate("MainWindow", "Initialize"))
        self.saveBtn.setText(_translate("MainWindow", "Save"))
        self.label_14.setText(_translate("MainWindow", "Rotation Speed:"))
        self.label_15.setText(_translate("MainWindow", "Animation Speed:"))
        self.calculateBtn.setText(_translate("MainWindow", "Run"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuAnimation.setTitle(_translate("MainWindow", "Animation"))
        self.about_Action.setText(_translate("MainWindow", "About"))
        self.close_Action.setText(_translate("MainWindow", "Close"))
        self.aniSave_Action.setText(_translate("MainWindow", "Save Current Figure"))
        self.aniPlay_Action.setText(_translate("MainWindow", "Play"))
        self.aniInitAction.setText(_translate("MainWindow", "Initialize"))

