# -*- coding: utf-8 -*- 
from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        self.infinity = 1.7976931348623157e+308
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(633, 379)
        MainWindow.adjustSize()
        self.setWindowIcon(QtGui.QIcon('icon.png'))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.centralwidget.setFont(font)
        self.centralwidget.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.controls = QtWidgets.QGroupBox(self.centralwidget)
        self.controls.setObjectName("controls")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.controls)
        self.verticalLayout.setObjectName("verticalLayout")
        self.formLayout_3 = QtWidgets.QFormLayout()
        self.formLayout_3.setObjectName("formLayout_3")
        self.label = QtWidgets.QLabel(self.controls)
        self.label.setObjectName("label")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.SpanningRole, self.label)
        self.stepSpin = QtWidgets.QSpinBox(self.controls)
        self.stepSpin.setMinimum(100)
        self.stepSpin.setMaximum(5000)
        self.stepSpin.setProperty("value", 500)
        self.stepSpin.setObjectName("stepSpin")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.stepSpin)
        self.stepSlide = QtWidgets.QSlider(self.controls)
        self.stepSlide.setMinimum(100)
        self.stepSlide.setMaximum(5000)
        self.stepSlide.setSingleStep(10)
        self.stepSlide.setPageStep(100)
        self.stepSlide.setProperty("value", 500)
        self.stepSlide.setOrientation(QtCore.Qt.Horizontal)
        self.stepSlide.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.stepSlide.setTickInterval(500)
        self.stepSlide.setObjectName("stepSlide")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.stepSlide)
        self.verticalLayout.addLayout(self.formLayout_3)
        self.line = QtWidgets.QFrame(self.controls)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label_5 = QtWidgets.QLabel(self.controls)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 2, 2, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.controls)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 1, 2, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.controls)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 2, 0, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.controls)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 3, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.controls)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 1, 0, 1, 1)
        self.radiusSpin = QtWidgets.QDoubleSpinBox(self.controls)
        self.radiusSpin.setObjectName("radiusSpin")
        self.radiusSpin.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.radiusSpin.setAutoFillBackground(False)
        self.radiusSpin.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.radiusSpin.setButtonSymbols(QtWidgets.QAbstractSpinBox.PlusMinus)
        self.radiusSpin.setDecimals(0)
        self.radiusSpin.setMinimum(1.0)
        self.radiusSpin.setMaximum(self.infinity)
        self.radiusSpin.setProperty("value", 100000.0)
        self.gridLayout.addWidget(self.radiusSpin, 3, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.controls)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 2)
        self.label_7 = QtWidgets.QLabel(self.controls)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 3, 2, 1, 1)
        self.omegaSpin = QtWidgets.QDoubleSpinBox(self.controls)
        self.omegaSpin.setMinimum(0)
        self.omegaSpin.setMaximum(self.infinity)
        self.omegaSpin.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.omegaSpin.setAutoFillBackground(False)
        self.omegaSpin.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.omegaSpin.setButtonSymbols(QtWidgets.QAbstractSpinBox.PlusMinus)
        self.omegaSpin.setDecimals(7)
        self.omegaSpin.setSingleStep(1e-05)
        self.omegaSpin.setProperty("value", 0.0000724)
        self.omegaSpin.setObjectName("omegaSpin")
        self.gridLayout.addWidget(self.omegaSpin, 1, 1, 1, 1)
        self.phiSpin = QtWidgets.QDoubleSpinBox(self.controls)
        self.phiSpin.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.phiSpin.setAutoFillBackground(False)
        self.phiSpin.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.phiSpin.setButtonSymbols(QtWidgets.QAbstractSpinBox.PlusMinus)
        self.phiSpin.setMinimum(-90.0)
        self.phiSpin.setMaximum(90.0)
        self.phiSpin.setProperty("value", 30.0)
        self.gridLayout.addWidget(self.phiSpin, 2, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.line_2 = QtWidgets.QFrame(self.controls)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout.addWidget(self.line_2)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_9 = QtWidgets.QLabel(self.controls)
        self.label_9.setObjectName("label_9")
        self.gridLayout_2.addWidget(self.label_9, 0, 0, 1, 2)
        self.label_13 = QtWidgets.QLabel(self.controls)
        self.label_13.setObjectName("label_13")
        self.gridLayout_2.addWidget(self.label_13, 0, 3, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.controls)
        self.label_10.setObjectName("label_10")
        self.gridLayout_2.addWidget(self.label_10, 1, 0, 1, 1)
        self.xSpin = QtWidgets.QDoubleSpinBox(self.controls)
        self.xSpin.setMinimum(-self.infinity)
        self.xSpin.setMaximum(self.infinity)
        self.xSpin.setObjectName("xSpin")
        self.gridLayout_2.addWidget(self.xSpin, 1, 1, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.controls)
        self.label_14.setObjectName("label_14")
        self.gridLayout_2.addWidget(self.label_14, 1, 2, 1, 1)
        self.uSpin = QtWidgets.QDoubleSpinBox(self.controls)
        self.uSpin.setMinimum(-self.infinity)
        self.uSpin.setMaximum(self.infinity)
        self.uSpin.setObjectName("uSpin")
        self.gridLayout_2.addWidget(self.uSpin, 1, 3, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.controls)
        self.label_11.setObjectName("label_11")
        self.gridLayout_2.addWidget(self.label_11, 2, 0, 1, 1)
        self.ySpin = QtWidgets.QDoubleSpinBox(self.controls)
        self.ySpin.setMinimum(-self.infinity)
        self.ySpin.setMaximum(self.infinity)
        self.ySpin.setObjectName("ySpin")
        self.gridLayout_2.addWidget(self.ySpin, 2, 1, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.controls)
        self.label_12.setObjectName("label_12")
        self.gridLayout_2.addWidget(self.label_12, 2, 2, 1, 1)
        self.vSpin = QtWidgets.QDoubleSpinBox(self.controls)
        self.vSpin.setMinimum(-self.infinity)
        self.vSpin.setMaximum(self.infinity)
        self.vSpin.setObjectName("vSpin")
        self.gridLayout_2.addWidget(self.vSpin, 2, 3, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_2)
        self.gridLayout_4.addWidget(self.controls, 0, 0, 2, 1)
        self.properties = QtWidgets.QGroupBox(self.centralwidget)
        self.properties.setObjectName("properties")
        self.formLayout = QtWidgets.QFormLayout(self.properties)
        self.formLayout.setObjectName("formLayout")
        self.label_15 = QtWidgets.QLabel(self.properties)
        self.label_15.setObjectName("label_15")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_15)
        self.fEdit = QtWidgets.QLineEdit(self.properties)
        self.fEdit.setEnabled(False)
        self.fEdit.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.fEdit.setReadOnly(True)
        self.fEdit.setObjectName("fEdit")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.fEdit)
        self.label_18 = QtWidgets.QLabel(self.properties)
        self.label_18.setObjectName("label_18")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_18)
        self.rossbyEdit = QtWidgets.QLineEdit(self.properties)
        self.rossbyEdit.setEnabled(False)
        self.rossbyEdit.setObjectName("rossbyEdit")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.rossbyEdit)
        self.label_19 = QtWidgets.QLabel(self.properties)
        self.label_19.setObjectName("label_19")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_19)
        self.tEdit = QtWidgets.QLineEdit(self.properties)
        self.tEdit.setEnabled(False)
        self.tEdit.setObjectName("tEdit")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.tEdit)
        self.gridLayout_4.addWidget(self.properties, 0, 1, 1, 1)
        self.figure = QtWidgets.QGroupBox(self.centralwidget)
        self.figure.setObjectName("figure")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.figure)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_20 = QtWidgets.QLabel(self.figure)
        self.label_20.setObjectName("label_20")
        self.gridLayout_3.addWidget(self.label_20, 1, 0, 1, 2)
        self.speedSpin = QtWidgets.QSpinBox(self.figure)
        self.speedSpin.setMinimum(1)
        self.speedSpin.setMaximum(100)
        self.speedSpin.setObjectName("speedSpin")
        self.gridLayout_3.addWidget(self.speedSpin, 3, 0, 1, 1)
        self.animateChk = QtWidgets.QCheckBox(self.figure)
        self.animateChk.setChecked(True)
        self.animateChk.setObjectName("animateChk")
        self.gridLayout_3.addWidget(self.animateChk, 0, 0, 1, 2)
        self.speedSlider = QtWidgets.QSlider(self.figure)
        self.speedSlider.setMinimum(1)
        self.speedSlider.setMaximum(100)
        self.speedSlider.setOrientation(QtCore.Qt.Horizontal)
        self.speedSlider.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.speedSlider.setTickInterval(10)
        self.speedSlider.setObjectName("speedSlider")
        self.gridLayout_3.addWidget(self.speedSlider, 3, 1, 1, 1)
        self.gridLayout_4.addWidget(self.figure, 1, 1, 1, 1)
        self.buttons = QtWidgets.QHBoxLayout()
        self.buttons.setObjectName("buttons")
        self.calculateBtn = QtWidgets.QPushButton(self.centralwidget)
        self.calculateBtn.setAutoDefault(True)
        self.calculateBtn.setDefault(True)
        self.calculateBtn.setObjectName("calculateBtn")
        self.buttons.addWidget(self.calculateBtn)
        self.stopBtn = QtWidgets.QPushButton(self.centralwidget)
        self.stopBtn.setEnabled(False)
        self.stopBtn.setObjectName("stopBtn")
        self.buttons.addWidget(self.stopBtn)
        self.showBtn = QtWidgets.QPushButton(self.centralwidget)
        self.showBtn.setEnabled(False)
        self.showBtn.setFlat(False)
        self.showBtn.setObjectName("showBtn")
        self.buttons.addWidget(self.showBtn)
        self.gridLayout_4.addLayout(self.buttons, 2, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 633, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.action_Exit = QtWidgets.QAction(MainWindow)
        self.action_Exit.setObjectName("action_Exit")
        self.menuFile.addAction(self.actionAbout)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.action_Exit)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        self.stepSpin.valueChanged['int'].connect(self.stepSlide.setValue)
        self.stepSlide.valueChanged['int'].connect(self.stepSpin.setValue)
        self.speedSpin.valueChanged['int'].connect(self.speedSlider.setValue)
        self.speedSlider.valueChanged['int'].connect(self.speedSpin.setValue)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Coriolis Trajectory"))
        self.controls.setTitle(_translate("MainWindow", "Controls"))
        self.label.setStatusTip(_translate("MainWindow", "Select the number of calculation steps."))
        self.label.setText(_translate("MainWindow", "Calculation Steps"))
        self.stepSpin.setStatusTip(_translate("MainWindow", "Select the number of calculation steps."))
        self.stepSlide.setStatusTip(_translate("MainWindow", "Select the number of calculation steps."))
        self.label_5.setText(_translate("MainWindow", "deg"))
        self.label_4.setText(_translate("MainWindow", "rad/s"))
        self.label_6.setText(_translate("MainWindow", "φ"))
        self.label_8.setText(_translate("MainWindow", "R"))
        self.label_3.setText(_translate("MainWindow", "Ω"))
        self.label_2.setText(_translate("MainWindow", "Geo - Characteristiscs"))
        self.label_7.setText(_translate("MainWindow", "m"))
        self.label_9.setText(_translate("MainWindow", "Initial Position"))
        self.label_13.setText(_translate("MainWindow", "Initial Velocity"))
        self.label_10.setText(_translate("MainWindow", "X"))
        self.label_14.setText(_translate("MainWindow", "U"))
        self.label_11.setText(_translate("MainWindow", "Y"))
        self.label_12.setText(_translate("MainWindow", "V"))
        self.properties.setTitle(_translate("MainWindow", "Properties"))
        self.label_15.setText(_translate("MainWindow", "Coriolis parameter f"))
        self.label_18.setText(_translate("MainWindow", "Rossby Number"))
        self.label_19.setText(_translate("MainWindow", "Oscillations Period"))
        self.figure.setTitle(_translate("MainWindow", "Figure Controls"))
        self.label_20.setText(_translate("MainWindow", "Animation Speed"))
        self.speedSpin.setStatusTip(_translate("MainWindow", "Lower value for faster animation."))
        self.animateChk.setText(_translate("MainWindow", "Animate"))
        self.speedSlider.setStatusTip(_translate("MainWindow", "Lower value for faster animation."))
        self.calculateBtn.setStatusTip(_translate("MainWindow", "Calculate the coriolis trajectory."))
        self.calculateBtn.setText(_translate("MainWindow", "Calculate"))
        self.stopBtn.setStatusTip(_translate("MainWindow", "Stop calculations."))
        self.stopBtn.setText(_translate("MainWindow", "Stop"))
        self.showBtn.setStatusTip(_translate("MainWindow", "Show the last calculated trajectory."))
        self.showBtn.setText(_translate("MainWindow", "Show Plot"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.actionAbout.setText(_translate("MainWindow", "About"))
        self.action_Exit.setText(_translate("MainWindow", "Exit"))
        self.label_19.setStatusTip(_translate("MainWindow", "Inertial oscillations period."))

